// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVnDH08FFl8ohJbcpW-4wDxcuIreK0Ly4',
    appId: '1:806245899506:web:e5dd9719b40afb6780446b',
    messagingSenderId: '806245899506',
    projectId: 'mytodoprojectflutter',
    authDomain: 'mytodoprojectflutter.firebaseapp.com',
    storageBucket: 'mytodoprojectflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlRejRG9yZWcPCT2bSqH2TQWfJRDxqwD0',
    appId: '1:806245899506:android:77a6ef669aaa301280446b',
    messagingSenderId: '806245899506',
    projectId: 'mytodoprojectflutter',
    storageBucket: 'mytodoprojectflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG867PTsgUEKlu4AN74VyFi2IQMIRXLQM',
    appId: '1:806245899506:ios:77840bd9b95ab05c80446b',
    messagingSenderId: '806245899506',
    projectId: 'mytodoprojectflutter',
    storageBucket: 'mytodoprojectflutter.appspot.com',
    iosClientId: '806245899506-o3c792636iqbvudmc2fhe9gnev3ie4a8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG867PTsgUEKlu4AN74VyFi2IQMIRXLQM',
    appId: '1:806245899506:ios:3a4d089c23808dde80446b',
    messagingSenderId: '806245899506',
    projectId: 'mytodoprojectflutter',
    storageBucket: 'mytodoprojectflutter.appspot.com',
    iosClientId: '806245899506-cmp3lijnf6c2tpg6nvprl1une6q7g1of.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
